#ifndef PARAMETERS_HPP
#define PARAMETERS_HPP

const int PHIL_LEN = 15;
const int VECTOR_OPTIMALIZATION = 10;
const int HOW_MANY_SUSHI_IN_CYCLE = 4;
const int HOW_MANY_SPAGGETTI_IN_CYCLE =1;
const int MILISECONDS_TO_COOK_DISH = 400;




#endif