#ifndef PARAMETERS_HPP
#define PARAMETERS_HPP

const int PHIL_LEN = 20;
const int VECTOR_OPTIMALIZATION = 5;
const int HOW_MANY_SUSHI_IN_CYCLE = 1;
const int HOW_MANY_SPAGGETTI_IN_CYCLE =2;
const int MILISECONDS_TO_COOK_DISH = 400;




#endif